name: Java CI
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
      - 'pom.xml'
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
      - name: Run tests
        run: mvn clean verify
      - name: Build with Maven
        run: mvn -B package --file pom.xml
